#
# Copyright (c) 2019 Hiroshi Hayakawa <hhiroshell@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

kind: Service
apiVersion: v1
metadata:
  name: ${project.artifactId}
  labels:
    app: ${project.artifactId}
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: 400Mbps
spec:
  type: LoadBalancer
  selector:
    app: ${project.artifactId}
  ports:
  - name: "http"
    port: 80
    targetPort: 8080
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ${project.artifactId}
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: ${project.artifactId}
        version: v1
    spec:
      containers:
      - name: ${project.artifactId}
        image: ${ocir.registory}/${ocir.tenancy}/${project.artifactId}:${project.version}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: atp-user
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: atp-user
                key: password
          - name: DATABASE_SERVICE
            value: "demo201902_low"
          - name: DATABASE_TNS_ADMIN
            value: "/etc/atp-wallet"
        volumeMounts:
        - name: atp-wallet
          mountPath: "/etc/atp-wallet"
        resources:
          requests:
            cpu: 200m
      volumes:
      - name: atp-wallet
        secret:
          secretName: atp-wallet
          defaultMode: 256
---
